# Generated by Django 5.0.3 on 2024-04-04 07:49

import django.db.models.deletion
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('iban', models.CharField(blank=True, max_length=255, null=True)),
                ('description', mdeditor.fields.MDTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('en_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('image', models.FileField(upload_to='')),
                ('alternative_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=370, null=True)),
                ('description', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('en_title', models.CharField(blank=True, max_length=370, null=True)),
                ('en_description', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('goal', models.BigIntegerField(verbose_name='Accumulation goal.')),
                (
                    'accumulated_current',
                    models.BigIntegerField(
                        verbose_name='How much money already accumulated.'
                    ),
                ),
                ('ua_timeline', models.BooleanField(blank=True, default=True)),
                ('en_timeline', models.BooleanField(blank=True, default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(to='main_app.account')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to='main_app.category',
                    ),
                ),
                ('images', models.ManyToManyField(to='main_app.projectimage')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
