# Generated by Django 5.0.6 on 2024-06-01 11:47

import django_resized.forms
import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='en_description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='en_statistic_additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='en_statistic_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='statistic_additional_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='statistic_counter',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='statistic_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=django_resized.forms.ResizedImageField(
                crop=None,
                force_format='JPEG',
                keep_meta=True,
                quality=-1,
                scale=None,
                size=[1000, 800],
                upload_to='',
            ),
        ),
    ]
