# Generated by Django 5.0.6 on 2024-06-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0002_category_description_category_en_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ManyToManyField(
                blank=True, null=True, to='main_app.projectimage'
            ),
        ),
    ]
