# Generated by Django 5.0.6 on 2024-06-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_project_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('en_name', models.CharField(max_length=255)),
                ('en_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Founder',
                'verbose_name_plural': 'Founders',
            },
        ),
    ]
