# Generated by Django 5.0.6 on 2024-06-02 12:46

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0004_founder'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', mdeditor.fields.MDTextField()),
                ('en_title', models.CharField(blank=True, max_length=255, null=True)),
                ('en_description', mdeditor.fields.MDTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ua_timeline', models.BooleanField(blank=True, default=True)),
                ('en_timeline', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
