# Generated by Django 5.0.6 on 2024-06-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='founder',
            name='picture',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='main_app.projectimage',
            ),
        ),
    ]
