# Generated by Django 5.0.6 on 2024-07-06 17:02

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Category = apps.get_model('main_app', 'Category')
    Category.objects.update(slug=models.F('en_name'))
    News = apps.get_model('main_app', 'News')
    News.objects.update(slug=models.F('title'))
    Project = apps.get_model('main_app', 'Project')
    Project.objects.update(slug=models.F('en_title'))


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0007_rename_projectimage_image_category_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func, reverse_func),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
